drift_frequency: 0.5        # Hertz
hfo_frequency: 80           # Hertz
notch_qa_factor: 20
highpass_butter_order: 5    # Hertz
lowpass_butter_order: 5     # Hertz

chb-mit:
  epoch_size: 2             # Seconds  
  f_samp: 256               # Hertz
  gain: 2.559375
  units: 0.000001           # Microvolts
  power_noise_frequency: 60 #Hertz

  seizure_type: null

  channels:
    - FP1-F7
    - F7-T7
    - T7-P7
    - P7-O1
    - FP1-F3
    - F3-C3
    - C3-P3
    - P3-O1
    - FP2-F4
    - F4-C4
    - C4-P4
    - P4-O2
    - FP2-F8
    - F8-T8
    - T8-P8
    - P8-O2


siena:
  #epoch_size: 2           # 2 seconds  
  f_samp: 512
  gain: 1
  units: 0.000001  # Microvolts  
  power_noise_frequency: 50 #Hertz

  seizure_type:
    PN00: IAS-T
    PN01: IAS-T
    PN03: IAS-T
    PN05: IAS-T
    PN06: IAS-T
    PN07: IAS-T
    PN09: IAS-T
    PN10: FBTC-F
    PN11: IAS-T
    PN12: IAS-T
    PN13: IAS-T
    PN14: WIAS-T
    PN16: IAS-T
    PN17: IAS-T

  channels:
    - Fp1
    - Fp2
    - F3
    - F4
    - F7
    - F8
    - T3
    - T4
    - T5
    - T6
    - O1
    - O2
    - C3
    - C4
    - P3
    - P4
    - Fz
    - Cz
    - Pz


tusz:
  #epoch_size: 2           # 2 seconds  
  f_samp: 512
  gain: 1
  units: 0.000001  # Microvolts
  power_noise_frequency: 60 #Hertz

  channels:
    - Fp1
    - Fp2
    - F3
    - F4
    - F7
    - F8
    - T3
    - T4
    - T5
    - T6
    - O1
    - O2
    - C3
    - C4
    - P3
    - P4
    - Fz
    - Cz
    - Pz