drift_frequency: 0.5        # Hertz
hfo_frequency: 80           # Hertz
notch_qa_factor: 20
drift_butter_order: 4
hfo_butter_order: 6 

####################################
eog_denoiser_segment_lenght: 40
eog_denoiser_sources_tol:         # Min and max number of sources to remove       
  - 0
  - 2
emg_denoiser_segment_lenght: 10
emg_denoiser_emg_freq: 20         # Frequency aproximately separating the EEG and EMG bands
emg_denoiser_ratio: 0.5             # Ratio of average power in EEG band to average power in the EMG band below which a
                                  # component will be considered to be EMG-related.
emg_denoiser_sources_tol:         # # Min and max number of sources to remove     
  - 0
  - 2
cssd_denoiser_segment_lenght: 20

####################################
preictal_min_length: 120
ictal_min_lenght: 10
postictal_min_lenght: 120

####################################
window_length: 1            # Seconds [5sec, 2sec, 1sec]
tolerance_length: 1         # Seconds
preictal_windows_start:
  - 60
  - 30
  - 10
  - 0
postictal_windows_start:
  - 0
  - 10
  - 30
  - 60
intra_windows_categories:
  - [preictal, 60, 1, "61s bef"]
  - [preictal, 30, 1, "31s bef"]
  - [preictal, 10, 2, "11s bef"]
  - [preictal, 0, 3, "1s bef"]
  - [ictal, 1, 1, "Onset"]
  - [ictal, 2, 1, "Middle"]
  - [ictal, -1, 2, "End"]
  - [postictal, 0, 1, "1s aft"]
  - [postictal, 10, 2, "11s aft"]
  - [postictal, 30, 3, "31s aft"]
  - [postictal, 60, 1, "61s aft"]

inter_windows_categories:
  - ["preictal"]
  - ["ictal"]
  - ["healthy"]

####################################
band_specifications:
  - {"cut_frequency": [0.5, 4], "order": 4}      # Delta band
  - {"cut_frequency": [4, 8],   "order": 4}      # Theta band
  - {"cut_frequency": [8, 12],  "order": 4}      # Alpha band
  - {"cut_frequency": [12, 30], "order": 4}      # Beta band
  - {"cut_frequency": [30, 70], "order": 4}      # Gamma band


####################################
bipolar_electrode_positions:
    Fp1-F7: [-0.48, 0.61]
    F7-T7: [-0.76, 0.23]
    T7-P7: [-0.76, -0.21]
    P7-O1: [-0.48, -0.60]
    Fp1-F3: [-0.22, 0.70]  
    F3-C3: [-0.37, 0.20]
    C3-P3: [-0.37, -0.21]
    P3-O1: [-0.22, -0.70]
    Fp2-F8: [0.48, 0.61]
    F8-T8: [0.76, 0.23]
    T8-P8: [0.76, -0.21]
    P8-O2: [0.44, -0.60]
    Fp2-F4: [0.22, 0.70]  
    F4-C4: [0.37, 0.23]
    C4-P4: [0.37, -0.21]
    P4-O2: [0.22, -0.70]
    F7-T3: [-0.76, 0.23]
    T3-T5: [-0.76, -0.21]
    T5-O1: [-0.48, -0.60]
    F8-T4: [0.76, 0.23]
    T4-T6: [0.76, -0.21]
    T6-O2: [0.44, -0.60]

####################################
chb-mit:
  epoch_size: 2             # Seconds  
  f_samp: 256               # Hertz
  gain: 2.559375
  units: 0.000001           # Microvolts
  ekg_units:
  power_noise_frequency: 60 #Hertz

  seizure_types:
    chb01: bilateral
    chb02: bilateral
    chb03: bilateral
    chb04: bilateral
    chb05: bilateral
    chb06: bilateral
    chb07: bilateral
    chb08: bilateral
    chb09: bilateral
    chb10: bilateral
    chb11: bilateral
    chb12: bilateral
    chb13: bilateral
    chb14: bilateral
    chb15: bilateral
    chb16: bilateral
    chb17: bilateral
    chb18: bilateral
    chb19: bilateral
    chb20: bilateral
    chb21: bilateral
    chb22: bilateral
    chb23: bilateral
    chb24: bilateral

  channels:
    - Fp1-F7
    - F7-T7
    - T7-P7
    - P7-O1
    - Fp1-F3
    - F3-C3
    - C3-P3
    - P3-O1
    - Fp2-F4
    - F4-C4
    - C4-P4
    - P4-O2
    - Fp2-F8
    - F8-T8
    - T8-P8
    - P8-O2
  
  univariate_channels_groups:
    left:
      - Fp1-F7
      - F7-T7
      - T7-P7
      - P7-O1
      - Fp1-F3
      - F3-C3
      - C3-P3
      - P3-O1
    right:
      - Fp2-F4
      - F4-C4
      - C4-P4
      - P4-O2
      - Fp2-F8
      - F8-T8
      - T8-P8
      - P8-O2


siena: 
  f_samp: 512
  gain: 1
  units: 0.000001  # Microvolts  
  ekg_units: 0.00001
  power_noise_frequency: 50 #Hertz

  valid_seizure_types:
    - right
    - left
    - bilateral

  seizure_types:
    PN00: right
    PN01: left
    PN03: right
    PN05: left
    PN06: left
    PN07: left
    PN09: left
    PN10: bilateral
    PN11: right
    PN12: left
    PN13: left
    PN14: left
    PN16: left
    PN17: right

  channels:
    - Fp1
    - Fp2
    - F3
    - F4
    - F7
    - F8
    - T3
    - T4
    - T5
    - T6
    - O1
    - O2
    - C3
    - C4
    - P3
    - P4
    - Fz
    - Cz
    - Pz

  univariate_channels_groups:
    left:
      - Fp1-F7
      - F7-T3
      - T3-T5
      - T5-O1
      - Fp1-F3
      - F3-C3
      - C3-P3
      - P3-O1
    right:
      - Fp2-F4
      - F4-C4
      - C4-P4
      - P4-O2
      - Fp2-F8
      - F8-T4
      - T4-T6
      - T6-O2


tusz:
  f_samp: 512
  gain: 1
  units: 0.000001  # Microvolts
  ekg_units:
  power_noise_frequency: 60 #Hertz

  valid_seizure_types:
    - left
    - right
    - bilateral
    #- absz   # Small amount of events - 6
    #- cpsz
    #- fnsz
    #- gnsz
    #- spsz   # Small amount of events - 1
    #- tcsz   # Small amount of events - 2
    #- tnsz

  channels:
    - Fp1
    - Fp2
    - F3
    - F4
    - F7
    - F8
    - T3
    - T4
    - T5
    - T6
    - O1
    - O2
    - C3
    - C4
    - P3
    - P4
    - Fz
    - Cz
    - Pz
  
  univariate_channels_groups:
    left:
      - Fp1-F7
      - F7-T3
      - T3-T5
      - T5-O1
      - Fp1-F3
      - F3-C3
      - C3-P3
      - P3-O1
    right:
      - Fp2-F4
      - F4-C4
      - C4-P4
      - P4-O2
      - Fp2-F8
      - F8-T4
      - T4-T6
      - T6-O2

tuep:
  f_samp: 512
  gain: 1
  units: 0.000001  # Microvolts
  ekg_units:
  power_noise_frequency: 60 #Hertz

  channels:
    - Fp1
    - Fp2
    - F3
    - F4
    - F7
    - F8
    - T3
    - T4
    - T5
    - T6
    - O1
    - O2
    - C3
    - C4
    - P3
    - P4
    - Fz
    - Cz
    - Pz
  
  univariate_channels_groups:
    left:
      - Fp1-F7
      - F7-T3
      - T3-T5
      - T5-O1
      - Fp1-F3
      - F3-C3
      - C3-P3
      - P3-O1
    right:
      - Fp2-F4
      - F4-C4
      - C4-P4
      - P4-O2
      - Fp2-F8
      - F8-T4
      - T4-T6
      - T6-O2


####################################

univariate_features:
  - kurtosis
  - skew
  - hjorth_mobility
  - hjorth_complexity
  - katz_fractal_dimension
  - approximate_entropy
  - power_spectral_density